### ISSUE TITLE
KinesisStreamSource seems to block when materialized

### ISSUE THREAD

**Issue by ludflu** [gilt/gfc-aws-kinesis#17]
Thanks for putting this kinesis -> akka adapter out there. Its a great starting point for what I need to do. I'm trying to merge a KinesisStreamSource with another stream. However, If I try to include a KinesisStreamSource in a akka-streams graph, it seems to block, and the rest of the flow never works.

```
  val consumerConfig = KinesisStreamConsumerConfig[IngestSegment](streamName,applicationName)
  val kinesisSource = KinesisStreamSource[IngestSegment](consumerConfig,timeout)
          .throttle(throttleItems,throttlePeriod.seconds,throttleItems,Shaping)
          .map(is => makeBinaryMessage(is.toByteArray))


  val mergeGraph = GraphDSL.create() { implicit builder =>
    import GraphDSL.Implicits._

    val mergeJunction = builder.add(Merge[Message](2))

    val _kinesisSource = builder.add(kinesisSource)
    val _queryFlow = builder.add(queryFlow)

    _kinesisSource ~> mergeJunction
    _queryFlow.out ~> mergeJunction

    FlowShape(_queryFlow.in, mergeJunction.out)
  }
```

Once materialized, this akka-streams graph blocks on the kinesis consumer.

However, if I replace the KinesisStreamSource with some dummy stream:

```
  val kinesisSource = Source(1 to 10000)
            .throttle(throttleItems,throttlePeriod.seconds,throttleItems,Shaping)
            .map(is => makeBinaryMessage(is.toString.getBytes))

```

Then, everything works as intended, the merge junction alternating between the two streams. Is KinesisStreamSource intended to block? Should I just run it in its own process and publish the resulting data via another actor or something? Thanks!

**Comment by mikegirkin** [comment]
@ludflu Yes, this is the intended behaviour.
Unfortunately KCL (Kinesis Client Library) is a blocking library, and there is no easy way to use it in a non-blocking way, it would require re-implementing half of the KCL. For the usecases we have here, at the moment, this is an acceptable solution.

**Comment by ludflu** [comment]
I just tried wrapping the "run" method in a future, and it seems like its working

https://github.com/gilt/gfc-aws-kinesis/blob/master/akka/src/main/scala/com/gilt/gfc/aws/kinesis/akka/KinesisStreamSource.scala#L41

`Future(consumer.run)
`
I'll report back once I've tested more thoroughly

**Comment by ludflu** [comment]
Yup, everything works perfectly if I just wrap it in a future. Would you like a PR? I could either create an alternate "NonBlockingKinesisStreamSource" or just wrap the call as above?

**Comment by mikegirkin** [comment]
Hi, @ludflu !

It would be nice if you submit a PR. I'll review it and merge ASAP

Cheers

**Comment by ludflu** [comment]
thanks a bunch!
