### ISSUE TITLE
Kinesis client (consumer and producer) don't work behind a proxy

### ISSUE THREAD

**Issue by vaslabs** [gilt/gfc-aws-kinesis#23]
Hello,

In our dev environment we work behind a proxy. I've made some changes to the codebase to allow optional proxy configuration.

This https://github.com/vaslabs/gfc-aws-kinesis/pull/1/files is working for us. Please let me know what you think.

An example usage of this for the consumer would be

```
val streamConfig = KinesisStreamConsumerConfig[ByteString](
      config.streamName,
      applicationName,
      regionName = Some(config.region),
      proxySettings = Some[ProxySettings](ProxySettings("192.168.10.101", 9000))
    )
```

**Comment by gheine** [comment]
@vaslabs mind opening a PR if you want this added here?

**Comment by vaslabs** [comment]
Will do, thanks

**Comment by vaslabs** [comment]
Hi,
After investigation we figured that we can use kinesalite and dynamodb for tests (even for dynamo streams). So that would make the proxies redundant and using those services locally with docker containers gives isolation.

So, I'll follow up with a PR for this since to make it work the endpoints in amazon kinesis client and the dynamodb client need to be over-written.
