### ISSUE TITLE
Are there plans to support the failoverTimeMillis config setting?

### ISSUE THREAD

**Issue by XerxesDGreat** [gilt/gfc-aws-kinesis#35]
Hi, we've been trying to use this lib in production after lots of QA time and have found that we likely have a need to bump up the `failoverTimeMillis` setting. 

https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibConfiguration.java#L380

The app runs extremely well for some time then suddenly connection is lost to one node which sets off a cascade of instability, leading to eventual termination. We've identified a couple issues within the app and are working to alleviate those, but due to the nature of our setup, we want to be able to support disconnects of more than 10 seconds. Thus, before I write it in myself, I wanted to see if you had any plans for doing so yourselves.

Thanks!

**Comment by gheine** [comment]
Hi, that sounds like a reasonable addition. Would you be able to send us a pull request?

**Comment by XerxesDGreat** [comment]
Yes, I will do that

**Comment by gheine** [comment]
Fixed in PR #36, released in v0.14.3
