### ISSUE TITLE
Dropped reads

### ISSUE THREAD

**Issue by dmunney** [gilt/gfc-aws-kinesis#43]
Not really an issue, I am curious if you've ever experienced dropped reads or writes without throwing an exception.  

Context:
I am using a `KCLWorkerRunner` to read from a Kinesis stream and index documents into Elasticsearch.  As a low-fidelity validation, I am comparing document counts from the source (an old version of Elasticsearch) and coming up with success rates between 99 and 100% over a modest 107k document count.  I have seen improvement in increasing the retry count, first from the default `3` to `10` and then to `100`.  I have yet to experience a consistent 100% and I was curious about your experience.

Also, if there is a better forum to discuss, please direct me there.

**Comment by gheine** [comment]
The kinesis semantics make it pretty much impossible to drop reads, as the stream iterator is only advanced on successful `getRecords`. However you'll need to monitor the rate at which you `putRecords` as not to exceed the shard limits esp wrt records per second but also wrt record size. See https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html

The `Future[KinesisPublisherBatchResult]` returned by `KinesisPublisher.publishBatch()` should give you information about the number of failed records, retry counts as well as reported error codes.

**Comment by dmunney** [comment]
Cloudwatch metrics seem to indicate that I am under the write rate and size.  I will take a closer look at `publishBatchResult` and see if I can gain any insights.  Thank you for your reply.
